### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mshariful** [scholarsportal/Dataverse-Data-Explorer#20] opened 2019-10-16 08:49 UTC
Hello,
I have installed Dataverse using  IQSS dataverse-docker: https://github.com/IQSS/dataverse-docker. It is running on http://localhost:8085/dataverse/root
Now I tried to install Dataverse-Data-Explorer using 
sudo curl -X POST -H 'Content-type: application/json' --upload-file dataExplorer.json http://localhost:8085/api/admin/externalTools
But I get this error:
{ status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}

I also tried 
sudo curl -X POST -H 'Content-type: application/json' --upload-file dataExplorer.json http://localhost:8080/api/admin/externalTools
In this case I get this message:
curl: (7) Failed to connect to localhost port 8080: Connection refused

Could you please help. Thank you very much. Regards, Sharif

**Comment by kaitlinnewson** [comment] 2019-10-21 18:23
@mshariful have you ssh'ed into the docker container before running the command? e.g. see this related issue: https://github.com/IQSS/dataverse-docker/issues/17

This issue appears to be related to dataverse/dataverse-docker and not the data explorer itself, so I'm going to close this, but feel free to re-open if you think the issue is with our tool.

**Closed by kaitlinnewson** 2019-10-21 18:23 UTC
